using System;
using System.CommandLine;
using System.IO;

using Hexalith.Folders.Cli.Errors;
using Hexalith.Folders.Client.Generated;

using Newtonsoft.Json;

namespace Hexalith.Folders.Cli.Commands;

/// <summary>
/// Factories for the per-command options shared across the seven groups, plus helpers that translate raw
/// option text into typed SDK inputs. Mutating commands get idempotency options; task-scoped commands get
/// <c>--task-id</c>; queries get freshness/pagination but never idempotency options (so passing one is an
/// unrecognized-argument parse error → exit 64).
/// </summary>
internal static class CommandOptions
{
    /// <summary>Creates the <c>--idempotency-key</c> option for a mutating command.</summary>
    /// <returns>A new option.</returns>
    public static Option<string?> IdempotencyKey() => new("--idempotency-key")
    {
        Description = "Caller-sourced idempotency key for this mutating operation.",
    };

    /// <summary>Creates the opt-in <c>--allow-auto-key</c> flag (generates a ULID, echoed to stderr).</summary>
    /// <returns>A new option.</returns>
    public static Option<bool> AllowAutoKey() => new("--allow-auto-key")
    {
        Description = "Generate an idempotency key (a ULID, printed to stderr) instead of supplying --idempotency-key.",
        DefaultValueFactory = _ => false,
    };

    /// <summary>Creates the <c>--task-id</c> option for a task-scoped command.</summary>
    /// <returns>A new option.</returns>
    public static Option<string?> TaskId() => new("--task-id")
    {
        Description = "Caller-provided task ID. Required for task-scoped operations; never generated by the CLI.",
    };

    /// <summary>Creates the <c>--freshness</c> read-consistency option for query commands.</summary>
    /// <returns>A new option.</returns>
    public static Option<string?> Freshness()
    {
        Option<string?> option = new("--freshness")
        {
            Description = "Requested read-consistency class.",
        };
        _ = option.AcceptOnlyFromAmong("snapshot_per_task", "read_your_writes", "eventually_consistent");
        return option;
    }

    /// <summary>Creates the <c>--cursor</c> pagination option.</summary>
    /// <returns>A new option.</returns>
    public static Option<string?> Cursor() => new("--cursor")
    {
        Description = "Opaque pagination cursor echoed from a previous page.",
    };

    /// <summary>Creates the <c>--limit</c> pagination option.</summary>
    /// <returns>A new option.</returns>
    public static Option<int?> Limit() => new("--limit")
    {
        Description = "Maximum number of items to return.",
    };

    /// <summary>Creates the <c>--filter</c> option.</summary>
    /// <returns>A new option.</returns>
    public static Option<string?> Filter() => new("--filter")
    {
        Description = "Metadata-only filter expression.",
    };

    /// <summary>
    /// Creates the <c>--request</c> option carrying the operation's spine request body. The value is inline
    /// JSON, <c>@path</c> to read a file, or <c>-</c> to read stdin. No new request fields are introduced.
    /// </summary>
    /// <returns>A new option.</returns>
    public static Option<string?> Request() => new("--request")
    {
        Description = "Request body as inline JSON, @path to a JSON file, or - to read JSON from stdin.",
    };

    /// <summary>Creates a required resource-identifier option (for example <c>--folder-id</c>).</summary>
    /// <param name="name">The option name (including leading dashes).</param>
    /// <param name="description">The option description.</param>
    /// <returns>A new required option.</returns>
    public static Option<string> RequiredId(string name, string description) => new(name)
    {
        Description = description,
        Required = true,
    };

    /// <summary>
    /// Reads and deserializes a request body of type <typeparamref name="T"/> from a <c>--request</c> value.
    /// Returns a default-constructed body when no value is supplied. Malformed JSON or an unreadable file is a
    /// pre-SDK usage error (<see cref="CliUsageException"/>) raised before any HTTP call. The metadata-only
    /// message never echoes the JSON content or path.
    /// </summary>
    /// <typeparam name="T">The spine request type.</typeparam>
    /// <param name="requestValue">The raw <c>--request</c> value.</param>
    /// <returns>The deserialized request body.</returns>
    public static T ReadBody<T>(string? requestValue)
        where T : new()
    {
        if (string.IsNullOrWhiteSpace(requestValue))
        {
            return new T();
        }

        string trimmed = requestValue.Trim();
        string json;
        try
        {
            json = trimmed switch
            {
                "-" => Console.In.ReadToEnd(),
                ['@', .. var path] => System.IO.File.ReadAllText(path),
                _ => trimmed,
            };
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new CliUsageException("The --request file could not be read.");
        }

        try
        {
            return JsonConvert.DeserializeObject<T>(json) ?? new T();
        }
        catch (JsonException)
        {
            throw new CliUsageException("The --request body is not valid JSON for this operation.");
        }
    }

    /// <summary>Maps a <c>--freshness</c> value to the typed read-consistency class.</summary>
    /// <param name="freshness">The raw option value.</param>
    /// <returns>The mapped class, or <see langword="null"/> when unspecified.</returns>
    public static ReadConsistencyClass? ParseFreshness(string? freshness) => freshness switch
    {
        "snapshot_per_task" => ReadConsistencyClass.Snapshot_per_task,
        "read_your_writes" => ReadConsistencyClass.Read_your_writes,
        "eventually_consistent" => ReadConsistencyClass.Eventually_consistent,
        _ => null,
    };
}
