using System;
using System.Security.Cryptography;

namespace Hexalith.Folders.Client.Convenience;

/// <summary>
/// Optional caller-registered source for correlation identifiers. When registered (see
/// <see cref="FoldersConvenienceServiceCollectionExtensions.AddFoldersCorrelationIdProvider{TProvider}"/>),
/// the resolver consults it before falling back to an SDK-generated ULID.
/// </summary>
/// <remarks>
/// This abstraction never affects task-ID or idempotency-key sourcing. Per the Adapter Parity Contract
/// (architecture.md decisions A-9/A-10), the SDK may synthesize a correlation ID but never a task ID and
/// never an idempotency key.
/// </remarks>
public interface ICorrelationIdProvider
{
    /// <summary>
    /// Returns a correlation identifier, or <see langword="null"/>/blank to defer to the SDK ULID fallback.
    /// </summary>
    /// <returns>A correlation identifier shaped as an <c>OpaqueIdentifier</c>, or <see langword="null"/>.</returns>
    string? GetCorrelationId();
}

/// <summary>
/// Sourcing convenience for the correlation- and task-ID header values consumed by the generated
/// Folders mutation operations. Implements the Adapter Parity Contract sourcing precedence so adapters
/// (SDK, CLI, MCP) propagate identical values for the same caller input.
/// </summary>
/// <remarks>
/// <para><b>Correlation ID</b> (the one value the SDK may synthesize): caller-provided value →
/// registered <see cref="ICorrelationIdProvider"/> → fresh SDK-generated ULID.</para>
/// <para><b>Task ID</b>: caller-provided only. The SDK never generates it and never downgrades a missing
/// value to empty; task-scoped operations (prepare, lock, file mutation, commit, release) require it.</para>
/// </remarks>
public static class CorrelationAndTaskId
{
    private const string CrockfordBase32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

    /// <summary>
    /// Resolves the correlation ID using parity precedence: explicit value, then provider, then a fresh ULID.
    /// </summary>
    /// <param name="explicitCorrelationId">A caller-supplied correlation ID, or <see langword="null"/>/blank.</param>
    /// <param name="provider">An optional registered correlation-ID provider.</param>
    /// <returns>A non-blank correlation identifier.</returns>
    public static string ResolveCorrelationId(string? explicitCorrelationId, ICorrelationIdProvider? provider = null)
    {
        if (!string.IsNullOrWhiteSpace(explicitCorrelationId))
        {
            return explicitCorrelationId;
        }

        string? fromProvider = provider?.GetCorrelationId();
        return !string.IsNullOrWhiteSpace(fromProvider) ? fromProvider : NewCorrelationId();
    }

    /// <summary>
    /// Validates that a task ID is present. The SDK never generates a task ID; absence is a caller error.
    /// </summary>
    /// <param name="taskId">A caller-supplied task ID.</param>
    /// <returns>The validated, non-blank task ID.</returns>
    /// <exception cref="InvalidOperationException">Thrown when <paramref name="taskId"/> is null or blank.</exception>
    public static string ResolveTaskId(string? taskId)
    {
        if (string.IsNullOrWhiteSpace(taskId))
        {
            // Fail closed: task ID is required for task-scoped operations and is never SDK-generated
            // or coerced to empty (Adapter Parity Contract decision A-10; Story 4.11 fail-closed rule).
            throw new InvalidOperationException(
                "A task ID is required for task-scoped Folders operations and is never generated by the SDK.");
        }

        return taskId;
    }

    /// <summary>
    /// Generates a fresh ULID-shaped correlation identifier (26-character Crockford Base32, sortable by time).
    /// </summary>
    /// <returns>A new correlation identifier valid as an <c>OpaqueIdentifier</c>.</returns>
    /// <remarks>
    /// Self-contained generator (no external dependency): 48-bit Unix-millisecond timestamp followed by
    /// 80 bits of cryptographic randomness, encoded as 26 Crockford Base32 characters.
    /// </remarks>
    public static string NewCorrelationId()
    {
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        Span<byte> randomness = stackalloc byte[10];
        RandomNumberGenerator.Fill(randomness);

        Span<char> buffer = stackalloc char[26];

        // Timestamp: 48 bits across the first 10 characters (top 2 of 50 bits are zero).
        for (int index = 9; index >= 0; index--)
        {
            buffer[index] = CrockfordBase32[(int)(timestamp & 0x1F)];
            timestamp >>= 5;
        }

        // Randomness: 80 bits across the last 16 characters, two 40-bit blocks of 8 characters each.
        int cursor = 10;
        for (int blockOffset = 0; blockOffset < 10; blockOffset += 5)
        {
            ulong block = 0;
            for (int byteIndex = 0; byteIndex < 5; byteIndex++)
            {
                block = (block << 8) | randomness[blockOffset + byteIndex];
            }

            for (int shift = 35; shift >= 0; shift -= 5)
            {
                buffer[cursor++] = CrockfordBase32[(int)((block >> shift) & 0x1F)];
            }
        }

        return new string(buffer);
    }
}
