namespace Hexalith.Folders.Providers.Forgejo;

internal enum ForgejoApiFailureCondition
{
    ValidationFailure,
    CancellationBeforeDispatch,
    ObservationCancelled,
    AuthenticationRequired,
    PermissionInsufficient,
    ContentsPermissionInsufficient,
    AdministrationPermissionInsufficient,
    NotFoundOrHidden,
    MissingRepository,
    MissingBranchOrPath,
    RepositoryConflict,
    ExistingEquivalent,
    DefaultBranchConflict,
    BranchProtectionConflict,
    UnsupportedRefOperation,
    RedirectCrossOrigin,
    RateLimit,
    ServerUnavailable,
    TimeoutDuringMutation,
    CancellationDuringMutation,
    AmbiguousMutationResponse,
    MalformedResponse,
    UnsupportedCapability,
    VersionIncompatible,
    SchemaDriftBreaking,
    UnexpectedTransportFailure,
}
