using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Hexalith.Folders.Client.Generated;
using Hexalith.Folders.Client.Idempotency;
using Newtonsoft.Json;
using Shouldly;
using Xunit;
using YamlDotNet.RepresentationModel;

namespace Hexalith.Folders.Client.Tests;

public sealed class ClientGenerationTests
{
    private static readonly string RepositoryRoot = LocateRepositoryRoot();

    [Fact]
    public void NswagConfigurationUsesContractSpineAsOnlyInput()
    {
        string configurationPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "nswag.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(configurationPath));

        JsonElement fromDocument = document.RootElement
            .GetProperty("documentGenerator")
            .GetProperty("fromDocument");
        JsonElement generator = document.RootElement
            .GetProperty("codeGenerators")
            .GetProperty("openApiToCSharpClient");

        fromDocument.GetProperty("url").GetString().ShouldBe("../../src/Hexalith.Folders.Contracts/openapi/hexalith.folders.v1.yaml");
        fromDocument.TryGetProperty("newLineBehavior", out _).ShouldBeFalse();
        generator.GetProperty("newLineBehavior").GetString().ShouldBe("LF");
        generator.GetProperty("output").GetString().ShouldBe("Generated/HexalithFoldersClient.g.cs");
        generator.GetProperty("namespace").GetString().ShouldBe("Hexalith.Folders.Client.Generated");
        generator.GetProperty("injectHttpClient").GetBoolean().ShouldBeTrue();
        generator.GetProperty("disposeHttpClient").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateSyncMethods").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateClientInterfaces").GetBoolean().ShouldBeTrue();
        generator.GetProperty("generateExceptionClasses").GetBoolean().ShouldBeTrue();
        generator.GetProperty("useBaseUrl").GetBoolean().ShouldBeFalse();
    }

    [Fact]
    public void GeneratedOutputCarriesStableSafeProvenance()
    {
        string generatedPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Generated", "HexalithFoldersIdempotencyHelpers.g.cs");
        string generated = File.ReadAllText(generatedPath);

        generated.ShouldContain("<auto-generated />");
        generated.ShouldContain("ContractSpineSha256");
        generated.ShouldContain("GenerationConfigurationSha256");
        generated.ShouldContain("GeneratedHelpersSha256");
        generated.ShouldNotContain(RepositoryRoot, Case.Insensitive);
        generated.ShouldNotContain("https://", Case.Insensitive);
        generated.ShouldNotContain("provider_token", Case.Insensitive);
        generated.ShouldNotContain("credential_material", Case.Insensitive);
    }

    [Fact]
    public void MutatingRequestsExposeIdempotencyHelpersAndQueriesDoNot()
    {
        OpenApiOperation[] operations = LoadOperations().ToArray();
        Assembly clientAssembly = typeof(CreateFolderRequest).Assembly;

        foreach (string schema in operations.Where(o => o.IdempotencyFields.Count > 0).Select(o => o.RequestSchema).WhereNotNull().Distinct(StringComparer.Ordinal))
        {
            Type type = clientAssembly.GetType("Hexalith.Folders.Client.Generated." + schema).ShouldNotBeNull();
            MethodInfo[] methods = type.GetMethods(BindingFlags.Instance | BindingFlags.Public).Where(m => m.Name == "ComputeIdempotencyHash").ToArray();
            methods.Length.ShouldBe(1, schema);
            methods[0].ReturnType.ShouldBe(typeof(string), schema);
        }

        foreach (string schema in operations.Where(o => o.IdempotencyFields.Count == 0).Select(o => o.RequestSchema).WhereNotNull().Distinct(StringComparer.Ordinal))
        {
            Type? type = clientAssembly.GetType("Hexalith.Folders.Client.Generated." + schema);
            if (type is not null)
            {
                type.GetMethods(BindingFlags.Instance | BindingFlags.Public).Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse(schema);
            }
        }
    }

    [Fact]
    public void BranchRefPolicyHelperUsesDeclaredSpineFields()
    {
        var request = new BranchRefPolicyRequest
        {
            AllowedRefPatterns = ["branch_ref_main"],
            DefaultRef = "branch_ref_main",
            PolicyRef = "branch_ref_default",
            ProtectedRefPatterns = ["branch_ref_release"],
            RepositoryBindingId = "repository_binding_01HZY7Z6N7J4Q2X8Y9V0RBI001",
            RequestSchemaVersion = BranchRefPolicyRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash("folder_01HZY7Z6N7J4Q2X8Y9V0FLD001").ShouldBe(ExpectedHash(
            "operation=ConfigureBranchRefPolicy",
            "field=branch_ref_policy.allowed_ref_patterns;present=true;value=j:[\"branch_ref_main\"]",
            "field=branch_ref_policy.default_ref;present=true;value=s:branch_ref_main",
            "field=branch_ref_policy.policy_ref;present=true;value=s:branch_ref_default",
            "field=branch_ref_policy.protected_ref_patterns;present=true;value=j:[\"branch_ref_release\"]",
            "field=folder_id;present=true;value=s:folder_01HZY7Z6N7J4Q2X8Y9V0FLD001",
            "field=repository_binding_id;present=true;value=s:repository_binding_01HZY7Z6N7J4Q2X8Y9V0RBI001"));
    }

    [Fact]
    public void FileMutationHelperSeparatesAddChangeAndRemove()
    {
        var add = CreateFileMutation(FileMutationRequestFileOperationKind.Add, "PutFileInline");
        var change = CreateFileMutation(FileMutationRequestFileOperationKind.Change, "PutFileInline");
        var remove = CreateFileMutation(FileMutationRequestFileOperationKind.Add, "metadataOnlyRemoval");
        remove.ContentHashReference = null;

        string workspaceId = "workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001";
        string taskId = "task_01HZY7Z6N7J4Q2X8Y9V0TSK001";

        add.ComputeIdempotencyHash(workspaceId, taskId).ShouldNotBe(change.ComputeIdempotencyHash(workspaceId, taskId));
        remove.ComputeIdempotencyHash(workspaceId, taskId).ShouldNotBe(add.ComputeIdempotencyHash(workspaceId, taskId));
    }

    [Fact]
    public void CreateFolderHelperUsesDeclaredLexicographicFields()
    {
        var request = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            ParentFolderId = null,
            ParentFolderIdSpecified = true,
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=CreateFolder",
            "field=folder_metadata.display_name;present=true;value=s:Synthetic Folder",
            "field=parent_folder_id;present=true;value=null",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void NullAndOmittedValuesProduceDifferentCanonicalHashes()
    {
        var nullParent = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            ParentFolderId = null,
            ParentFolderIdSpecified = true,
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        var omittedParent = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        nullParent.ComputeIdempotencyHash().ShouldNotBe(omittedParent.ComputeIdempotencyHash());
    }

    [Fact]
    public void FileMutationHelpersIgnoreRawContentAndLocalPaths()
    {
        FileMutationRequest first = CreateFileMutation(FileMutationRequestFileOperationKind.Add, "PutFileInline");
        FileMutationRequest second = CreateFileMutation(first.FileOperationKind, first.TransportOperation);

        first.ComputeIdempotencyHash("workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001", "task_01HZY7Z6N7J4Q2X8Y9V0TSK001")
            .ShouldBe(second.ComputeIdempotencyHash("workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001", "task_01HZY7Z6N7J4Q2X8Y9V0TSK001"));
    }

    [Fact]
    public void StaleGeneratedOutputDetectionUsesAllContentHashes()
    {
        HexalithFoldersGeneratedArtifacts.VerifyCurrentDetailed(RepositoryRoot).IsCurrent.ShouldBeTrue();
        HexalithFoldersGeneratedArtifacts.VerifyCurrent("relative-root").ShouldBeFalse();

        string spine = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Contracts", "openapi", "hexalith.folders.v1.yaml"));
        string configuration = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "nswag.json"));
        string helpers = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Generated", "HexalithFoldersIdempotencyHelpers.g.cs"));

        HexalithFoldersGeneratedArtifacts.IsCurrent(spine + "\n# controlled stale-output test", configuration, helpers).ShouldBeFalse();
        HexalithFoldersGeneratedArtifacts.IsCurrent(spine, configuration.Replace("LF", "CRLF", StringComparison.Ordinal), helpers).ShouldBeFalse();
        HexalithFoldersGeneratedArtifacts.IsCurrent(spine, configuration, helpers + "\n// controlled stale-output test").ShouldBeFalse();
    }

    [Fact]
    public void CanonicalHasherFailsClosedForMalformedMetadata()
    {
        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Test", [
            new IdempotencyField("z_field", true, "last"),
            new IdempotencyField("a_field", true, "first"),
        ]));

        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Test", [
            new IdempotencyField("a_field", true, "first"),
            new IdempotencyField("a_field", true, "duplicate"),
        ]));

        Should.Throw<Newtonsoft.Json.JsonReaderException>(() => HexalithIdempotencyHasher.NormalizeJsonText("{\"operation_id\":\"a\",\"operation_id\":\"b\"}"));
    }

    [Fact]
    public void IdempotencyEncodingCorpusIsConsumedForParserPolicyCases()
    {
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(Path.Combine(RepositoryRoot, "tests", "fixtures", "idempotency-encoding-corpus.json")));
        JsonElement[] cases = document.RootElement.GetProperty("cases").EnumerateArray().ToArray();

        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("NFC");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("NFD");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("ULID casing");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("percent-encoding");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("duplicate-json-key");
        cases.All(c => c.GetProperty("synthetic_data_only").GetBoolean()).ShouldBeTrue();
        cases.Any(c => c.GetProperty("contains_payload_material").GetBoolean()).ShouldBeFalse();

        JsonElement duplicateKey = cases.Single(c => c.GetProperty("category").GetString() == "duplicate-json-key");
        Should.Throw<Newtonsoft.Json.JsonReaderException>(() => HexalithIdempotencyHasher.NormalizeJsonText(duplicateKey.GetProperty("input").GetString()!));
    }

    [Fact]
    public void ApiExceptionExposesTypedProblemDetails()
    {
        var problem = new ProblemDetails
        {
            Category = CanonicalErrorCategory.Validation_error,
            ClientAction = ProblemDetailsClientAction.Revise_request,
            Code = "validation_error",
            CorrelationId = "correlation_01HZY7Z6N7J4Q2X8Y9V0COR001",
            Message = "Synthetic validation failure.",
            Retryable = false,
        };

        var typed = new HexalithFoldersApiException<ProblemDetails>("message", 400, "{}", new Dictionary<string, IEnumerable<string>>(), problem, null!);
        typed.ProblemDetails.ShouldBeSameAs(problem);

        string response = JsonConvert.SerializeObject(problem);
        var untyped = new HexalithFoldersApiException("message", 400, response, new Dictionary<string, IEnumerable<string>>(), null!);
        untyped.ProblemDetails.ShouldNotBeNull().Code.ShouldBe("validation_error");
    }

    [Fact]
    public void HelperGeneratorProjectIsBuildTimeInput()
    {
        string project = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Hexalith.Folders.Client.csproj");
        string content = File.ReadAllText(project);

        content.ShouldContain("GenerateHexalithFoldersIdempotencyHelpers");
        content.ShouldContain("Hexalith.Folders.Client.Generation.csproj");
        content.ShouldContain("$(HexalithFoldersGeneratedHelpers)");
    }

    private static FileMutationRequest CreateFileMutation(FileMutationRequestFileOperationKind kind, object transportOperation) =>
        new()
        {
            FileOperationKind = kind,
            TransportOperation = transportOperation,
            OperationId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
            PathMetadata = new PathMetadata
            {
                NormalizedPath = "docs/readme.md",
                DisplayName = "readme.md",
                PathPolicyClass = "metadata_only",
                UnicodeNormalization = PathMetadataUnicodeNormalization.NFC,
            },
            ContentHashReference = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            RequestSchemaVersion = "v1",
        };

    private static string ExpectedHash(params string[] lines)
    {
        string canonical = string.Join('\n', lines);
        byte[] digest = SHA256.HashData(Encoding.UTF8.GetBytes(canonical));
        return "sha256:" + Convert.ToHexString(digest).ToLowerInvariant();
    }

    private static IReadOnlyList<OpenApiOperation> LoadOperations()
    {
        using StreamReader reader = File.OpenText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Contracts", "openapi", "hexalith.folders.v1.yaml"));
        YamlStream yaml = new();
        yaml.Load(reader);
        YamlMappingNode root = yaml.Documents[0].RootNode.ShouldBeOfType<YamlMappingNode>();
        List<OpenApiOperation> operations = [];

        foreach (KeyValuePair<YamlNode, YamlNode> pathEntry in RequiredMapping(root, "paths").Children)
        {
            YamlMappingNode path = pathEntry.Value.ShouldBeOfType<YamlMappingNode>();
            foreach (KeyValuePair<YamlNode, YamlNode> methodEntry in path.Children)
            {
                string method = methodEntry.Key.ShouldBeOfType<YamlScalarNode>().Value ?? string.Empty;
                if (method is not ("get" or "post" or "put" or "patch" or "delete"))
                {
                    continue;
                }

                YamlMappingNode operation = methodEntry.Value.ShouldBeOfType<YamlMappingNode>();
                string operationId = RequiredScalar(operation, "operationId");
                string? requestSchema = TryReadRequestSchema(operation);
                IReadOnlyList<string> fields = ReadStringSequence(operation, "x-hexalith-idempotency-equivalence");
                operations.Add(new OpenApiOperation(operationId, requestSchema, fields));
            }
        }

        return operations;
    }

    private static string? TryReadRequestSchema(YamlMappingNode operation)
    {
        if (!operation.Children.TryGetValue(new YamlScalarNode("requestBody"), out YamlNode? requestBodyNode))
        {
            return null;
        }

        YamlMappingNode requestBody = requestBodyNode.ShouldBeOfType<YamlMappingNode>();
        YamlMappingNode content = RequiredMapping(requestBody, "content");
        YamlMappingNode json = RequiredMapping(content, "application/json");
        YamlMappingNode schema = RequiredMapping(json, "schema");
        return RequiredScalar(schema, "$ref").Split('/').Last();
    }

    private static IReadOnlyList<string> ReadStringSequence(YamlMappingNode mapping, string key)
    {
        if (!mapping.Children.TryGetValue(new YamlScalarNode(key), out YamlNode? value))
        {
            return [];
        }

        return value.ShouldBeOfType<YamlSequenceNode>().Children.Select(node => node.ShouldBeOfType<YamlScalarNode>().Value ?? string.Empty).ToArray();
    }

    private static YamlMappingNode RequiredMapping(YamlMappingNode mapping, string key)
    {
        mapping.Children.TryGetValue(new YamlScalarNode(key), out YamlNode? value).ShouldBeTrue(key);
        return value.ShouldBeOfType<YamlMappingNode>();
    }

    private static string RequiredScalar(YamlMappingNode mapping, string key)
    {
        mapping.Children.TryGetValue(new YamlScalarNode(key), out YamlNode? value).ShouldBeTrue(key);
        return value.ShouldBeOfType<YamlScalarNode>().Value ?? string.Empty;
    }

    private static string LocateRepositoryRoot()
    {
        string? metadata = typeof(ClientGenerationTests).Assembly
            .GetCustomAttributes<AssemblyMetadataAttribute>()
            .FirstOrDefault(attribute => attribute.Key == "RepositoryRoot")
            ?.Value;
        ArgumentException.ThrowIfNullOrWhiteSpace(metadata);
        return Path.GetFullPath(metadata);
    }

    private sealed record OpenApiOperation(string OperationId, string? RequestSchema, IReadOnlyList<string> IdempotencyFields);
}

internal static class EnumerableExtensions
{
    public static IEnumerable<T> WhereNotNull<T>(this IEnumerable<T?> values)
        where T : class
    {
        foreach (T? value in values)
        {
            if (value is not null)
            {
                yield return value;
            }
        }
    }
}
