using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Hexalith.Folders.Client.Generated;
using Hexalith.Folders.Client.Idempotency;
using Shouldly;
using Xunit;

namespace Hexalith.Folders.Client.Tests;

public sealed class ClientGenerationTests
{
    private static readonly string RepositoryRoot = LocateRepositoryRoot();

    [Fact]
    public void NswagConfigurationUsesContractSpineAsOnlyInput()
    {
        string configurationPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "nswag.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(configurationPath));

        JsonElement fromDocument = document.RootElement
            .GetProperty("documentGenerator")
            .GetProperty("fromDocument");
        JsonElement generator = document.RootElement
            .GetProperty("codeGenerators")
            .GetProperty("openApiToCSharpClient");

        fromDocument.GetProperty("url").GetString().ShouldBe("../../src/Hexalith.Folders.Contracts/openapi/hexalith.folders.v1.yaml");
        generator.GetProperty("output").GetString().ShouldBe("Generated/HexalithFoldersClient.g.cs");
        generator.GetProperty("namespace").GetString().ShouldBe("Hexalith.Folders.Client.Generated");
        generator.GetProperty("injectHttpClient").GetBoolean().ShouldBeTrue();
        generator.GetProperty("disposeHttpClient").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateSyncMethods").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateClientInterfaces").GetBoolean().ShouldBeTrue();
        generator.GetProperty("generateExceptionClasses").GetBoolean().ShouldBeTrue();
        generator.GetProperty("useBaseUrl").GetBoolean().ShouldBeFalse();
    }

    [Fact]
    public void GeneratedOutputCarriesStableSafeProvenance()
    {
        string generatedPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Generated", "HexalithFoldersIdempotencyHelpers.g.cs");
        string generated = File.ReadAllText(generatedPath);

        generated.ShouldContain("<auto-generated />");
        generated.ShouldContain("ContractSpineSha256");
        generated.ShouldContain("GenerationConfigurationSha256");
        generated.ShouldNotContain(RepositoryRoot, Case.Insensitive);
        generated.ShouldNotContain("https://", Case.Insensitive);
        generated.ShouldNotContain("provider_token", Case.Insensitive);
        generated.ShouldNotContain("credential_material", Case.Insensitive);
    }

    [Fact]
    public void MutatingRequestsExposeIdempotencyHelpersAndQueriesDoNot()
    {
        typeof(CreateFolderRequest).GetMethod("ComputeIdempotencyHash", Type.EmptyTypes).ShouldNotBeNull();
        typeof(FileMutationRequest).GetMethod("ComputeIdempotencyHash", [typeof(string), typeof(string)]).ShouldNotBeNull();

        typeof(FolderLifecycleStatus).GetMethod("ComputeIdempotencyHash", Type.EmptyTypes).ShouldBeNull();
        typeof(FileTreeResult).GetMethod("ComputeIdempotencyHash", Type.EmptyTypes).ShouldBeNull();
    }

    [Fact]
    public void CreateFolderHelperUsesDeclaredLexicographicFields()
    {
        var request = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            ParentFolderId = null,
            ParentFolderIdSpecified = true,
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=CreateFolder",
            "field=folder_metadata.display_name;present=true;value=s:Synthetic Folder",
            "field=parent_folder_id;present=true;value=null",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void NullAndOmittedValuesProduceDifferentCanonicalHashes()
    {
        var nullParent = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            ParentFolderId = null,
            ParentFolderIdSpecified = true,
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        var omittedParent = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        nullParent.ComputeIdempotencyHash().ShouldNotBe(omittedParent.ComputeIdempotencyHash());
    }

    [Fact]
    public void FileMutationHelpersIgnoreRawContentAndLocalPaths()
    {
        var first = new FileMutationRequest
        {
            FileOperationKind = FileMutationRequestFileOperationKind.Add,
            OperationId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
            PathMetadata = new PathMetadata
            {
                NormalizedPath = "docs/readme.md",
                DisplayName = "readme.md",
                PathPolicyClass = "metadata_only",
                UnicodeNormalization = PathMetadataUnicodeNormalization.NFC,
            },
            ContentHashReference = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            RequestSchemaVersion = "v1",
        };

        var second = new FileMutationRequest
        {
            FileOperationKind = first.FileOperationKind,
            OperationId = first.OperationId,
            PathMetadata = first.PathMetadata,
            ContentHashReference = first.ContentHashReference,
            RequestSchemaVersion = first.RequestSchemaVersion,
        };

        first.ComputeIdempotencyHash("workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001", "task_01HZY7Z6N7J4Q2X8Y9V0TSK001")
            .ShouldBe(second.ComputeIdempotencyHash("workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001", "task_01HZY7Z6N7J4Q2X8Y9V0TSK001"));
    }

    [Fact]
    public void StaleGeneratedOutputDetectionUsesContentHashes()
    {
        HexalithFoldersGeneratedArtifacts.VerifyCurrent(RepositoryRoot).ShouldBeTrue();

        string spine = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Contracts", "openapi", "hexalith.folders.v1.yaml"));
        string changedSpine = spine + Environment.NewLine + "# controlled stale-output test";
        HexalithFoldersGeneratedArtifacts.IsCurrent(changedSpine, File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "nswag.json"))).ShouldBeFalse();
    }

    private static string ExpectedHash(params string[] lines)
    {
        string canonical = string.Join('\n', lines);
        byte[] digest = SHA256.HashData(Encoding.UTF8.GetBytes(canonical));
        return "sha256:" + Convert.ToHexString(digest).ToLowerInvariant();
    }

    private static string LocateRepositoryRoot()
    {
        DirectoryInfo? current = new(AppContext.BaseDirectory);
        while (current is not null)
        {
            if (File.Exists(Path.Combine(current.FullName, "Hexalith.Folders.slnx")))
            {
                return current.FullName;
            }

            current = current.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root.");
    }
}
