using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;
using Hexalith.Folders.Client.Generated;
using Hexalith.Folders.Client.Generation.Shared;
using Hexalith.Folders.Client.Idempotency;
using Newtonsoft.Json;
using Shouldly;
using Xunit;
using YamlDotNet.RepresentationModel;
using static Hexalith.Folders.Client.Generation.Shared.YamlContractLoader;

namespace Hexalith.Folders.Client.Tests;

public sealed class ClientGenerationTests
{
    private static readonly string RepositoryRoot = LocateRepositoryRoot();

    [Fact]
    public void NswagConfigurationUsesContractSpineAsOnlyInput()
    {
        string configurationPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "nswag.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(configurationPath));

        JsonElement fromDocument = document.RootElement
            .GetProperty("documentGenerator")
            .GetProperty("fromDocument");
        JsonElement generator = document.RootElement
            .GetProperty("codeGenerators")
            .GetProperty("openApiToCSharpClient");

        fromDocument.GetProperty("url").GetString().ShouldBe("../../src/Hexalith.Folders.Contracts/openapi/hexalith.folders.v1.yaml");
        fromDocument.TryGetProperty("newLineBehavior", out _).ShouldBeFalse();
        generator.GetProperty("newLineBehavior").GetString().ShouldBe("LF");
        generator.GetProperty("output").GetString().ShouldBe("Generated/HexalithFoldersClient.g.cs");
        generator.GetProperty("namespace").GetString().ShouldBe("Hexalith.Folders.Client.Generated");
        generator.GetProperty("injectHttpClient").GetBoolean().ShouldBeTrue();
        generator.GetProperty("disposeHttpClient").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateSyncMethods").GetBoolean().ShouldBeFalse();
        generator.GetProperty("generateClientInterfaces").GetBoolean().ShouldBeTrue();
        generator.GetProperty("generateExceptionClasses").GetBoolean().ShouldBeTrue();
        generator.GetProperty("useBaseUrl").GetBoolean().ShouldBeFalse();
    }

    [Fact]
    public void GeneratedOutputCarriesStableSafeProvenance()
    {
        string generatedPath = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Generated", "HexalithFoldersIdempotencyHelpers.g.cs");
        string generated = File.ReadAllText(generatedPath);

        generated.ShouldContain("<auto-generated />");
        generated.ShouldContain("ContractSpineSha256");
        generated.ShouldContain("GenerationConfigurationSha256");
        generated.ShouldContain("GeneratedHelpersSha256");
        generated.ShouldNotContain(RepositoryRoot, Case.Insensitive);
        generated.ShouldNotContain("https://", Case.Insensitive);
        generated.ShouldNotContain("provider_token", Case.Insensitive);
        generated.ShouldNotContain("credential_material", Case.Insensitive);
    }

    [Fact]
    public void MutatingRequestsExposeIdempotencyHelpersAndQueriesDoNot()
    {
        OpenApiOperation[] operations = LoadOperations().ToArray();
        Assembly clientAssembly = typeof(CreateFolderRequest).Assembly;

        foreach (IGrouping<string, OpenApiOperation> group in operations.Where(o => o.IdempotencyFields.Count > 0).Where(o => o.RequestSchema is not null).GroupBy(o => o.RequestSchema!, StringComparer.Ordinal))
        {
            Type type = clientAssembly.GetType("Hexalith.Folders.Client.Generated." + group.Key).ShouldNotBeNull();
            MethodInfo[] methods = type.GetMethods(BindingFlags.Instance | BindingFlags.Public).Where(m => m.Name == "ComputeIdempotencyHash").ToArray();
            methods.Length.ShouldBe(1, group.Key);
            methods[0].ReturnType.ShouldBe(typeof(string), group.Key);

            OpenApiParameter[] expectedSpineParameters = group
                .SelectMany(o => o.Parameters.Where(p => o.IdempotencyFields.Contains(p.Field, StringComparer.Ordinal)))
                .GroupBy(p => p.Field, StringComparer.Ordinal)
                .Select(g => g.OrderBy(p => p.Name, StringComparer.Ordinal).First())
                .ToArray();
            string[] expectedParameterTypes = expectedSpineParameters.Select(_ => typeof(string).FullName!).ToArray();
            string[] expectedParameterNames = expectedSpineParameters.Select(p => ToCamelCase(p.Field)).ToArray();

            ParameterInfo[] actualParameters = methods[0].GetParameters();
            actualParameters.Select(p => p.ParameterType.FullName).ToArray().ShouldBe(expectedParameterTypes, group.Key);
            actualParameters.Select(p => p.Name).ToArray().ShouldBe(expectedParameterNames, group.Key + " parameter names must match spine path-parameter declaration order");
        }

        foreach (string schema in operations.Where(o => o.IdempotencyFields.Count == 0).Select(o => o.RequestSchema).WhereNotNull().Distinct(StringComparer.Ordinal))
        {
            Type type = clientAssembly.GetType("Hexalith.Folders.Client.Generated." + schema).ShouldNotBeNull();
            type.GetMethods(BindingFlags.Instance | BindingFlags.Public).Any(m => m.Name == "ComputeIdempotencyHash").ShouldBeFalse(schema);
        }
    }

    [Fact]
    public void BranchRefPolicyHelperUsesDeclaredSpineFields()
    {
        var request = new BranchRefPolicyRequest
        {
            AllowedRefPatterns = ["branch_ref_main"],
            DefaultRef = "branch_ref_main",
            PolicyRef = "branch_ref_default",
            ProtectedRefPatterns = ["branch_ref_release"],
            RepositoryBindingId = "repository_binding_01HZY7Z6N7J4Q2X8Y9V0RBI001",
            RequestSchemaVersion = BranchRefPolicyRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash("folder_01HZY7Z6N7J4Q2X8Y9V0FLD001").ShouldBe(ExpectedHash(
            "operation=ConfigureBranchRefPolicy",
            "field=branch_ref_policy.allowed_ref_patterns;present=true;value=j:[\"branch_ref_main\"]",
            "field=branch_ref_policy.default_ref;present=true;value=s:branch_ref_main",
            "field=branch_ref_policy.policy_ref;present=true;value=s:branch_ref_default",
            "field=branch_ref_policy.protected_ref_patterns;present=true;value=j:[\"branch_ref_release\"]",
            "field=folder_id;present=true;value=s:folder_01HZY7Z6N7J4Q2X8Y9V0FLD001",
            "field=repository_binding_id;present=true;value=s:repository_binding_01HZY7Z6N7J4Q2X8Y9V0RBI001"));
    }

    [Fact]
    public void FileMutationHelperSeparatesAddChangeAndRemove()
    {
        var add = CreateFileMutation(FileMutationRequestFileOperationKind.Add, "PutFileInline");
        var change = CreateFileMutation(FileMutationRequestFileOperationKind.Change, "PutFileInline");
        var remove = CreateFileMutation((FileMutationRequestFileOperationKind)2, "metadataOnlyRemoval");
        remove.ContentHashReference = null;

        string workspaceId = "workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001";
        string taskId = "task_01HZY7Z6N7J4Q2X8Y9V0TSK001";

        add.ComputeIdempotencyHash(workspaceId, taskId).ShouldNotBe(change.ComputeIdempotencyHash(workspaceId, taskId));
        remove.ComputeIdempotencyHash(workspaceId, taskId).ShouldNotBe(add.ComputeIdempotencyHash(workspaceId, taskId));
    }

    [Fact]
    public void CreateFolderHelperUsesDeclaredLexicographicFields()
    {
        var request = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            ParentFolderId = null,
            ParentFolderIdSpecified = true,
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        request.ComputeIdempotencyHash().ShouldBe(ExpectedHash(
            "operation=CreateFolder",
            "field=folder_metadata.display_name;present=true;value=s:Synthetic Folder",
            "field=parent_folder_id;present=true;value=null",
            "field=request_schema_version;present=true;value=s:v1"));
    }

    [Fact]
    public void NullAndOmittedValuesProduceDifferentCanonicalHashes()
    {
        var nullParent = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            ParentFolderId = null,
            ParentFolderIdSpecified = true,
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        var omittedParent = new CreateFolderRequest
        {
            FolderMetadata = new FolderMetadata
            {
                DisplayName = "Synthetic Folder",
            },
            RequestSchemaVersion = CreateFolderRequestRequestSchemaVersion.V1,
        };

        nullParent.ComputeIdempotencyHash().ShouldNotBe(omittedParent.ComputeIdempotencyHash());
    }

    [Fact]
    public void FileMutationHelpersIgnoreRawContentAndLocalPaths()
    {
        FileMutationRequest first = CreateFileMutation(FileMutationRequestFileOperationKind.Add, "PutFileInline");
        FileMutationRequest second = CreateFileMutation(first.FileOperationKind, first.TransportOperation);

        first.ComputeIdempotencyHash("workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001", "task_01HZY7Z6N7J4Q2X8Y9V0TSK001")
            .ShouldBe(second.ComputeIdempotencyHash("workspace_01HZY7Z6N7J4Q2X8Y9V0WKS001", "task_01HZY7Z6N7J4Q2X8Y9V0TSK001"));
    }

    [Fact]
    public void StaleGeneratedOutputDetectionUsesAllContentHashes()
    {
        HexalithFoldersGeneratedArtifacts.VerifyCurrentDetailed(RepositoryRoot).IsCurrent.ShouldBeTrue();
        HexalithFoldersGeneratedArtifacts.VerifyCurrent("relative-root").ShouldBeFalse();

        string spine = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Contracts", "openapi", "hexalith.folders.v1.yaml"));
        string configuration = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "nswag.json"));
        string helpers = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Generated", "HexalithFoldersIdempotencyHelpers.g.cs"));

        HexalithFoldersGeneratedArtifacts.IsCurrent(spine + "\n# controlled stale-output test", configuration, helpers).ShouldBeFalse();
        HexalithFoldersGeneratedArtifacts.IsCurrent(spine, configuration.Replace("LF", "CRLF", StringComparison.Ordinal), helpers).ShouldBeFalse();
        HexalithFoldersGeneratedArtifacts.IsCurrent(spine, configuration, helpers + "\n// controlled stale-output test").ShouldBeFalse();
    }

    [Fact]
    public void HelperGenerationTargetRegeneratesWhenContractSpineChanges()
    {
        string tempRoot = Path.Combine(Path.GetTempPath(), "hexalith-folders-generation-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempRoot);
        try
        {
            string output = Path.Combine(tempRoot, "HexalithFoldersIdempotencyHelpers.g.cs");
            string mutatedSpine = Path.Combine(tempRoot, "hexalith.folders.v1.yaml");
            string originalSpine = File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Contracts", "openapi", "hexalith.folders.v1.yaml"));
            File.WriteAllText(mutatedSpine, originalSpine + "\n# controlled regeneration input change\n", Encoding.UTF8);

            string project = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Hexalith.Folders.Client.csproj");
            using System.Diagnostics.Process process = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
            {
                FileName = "dotnet",
                Arguments = $"msbuild \"{project}\" /t:GenerateHexalithFoldersIdempotencyHelpers /p:HexalithFoldersContractSpine=\"{mutatedSpine}\" /p:HexalithFoldersGeneratedHelpers=\"{output}\"",
                RedirectStandardError = true,
                RedirectStandardOutput = true,
                UseShellExecute = false,
            }) ?? throw new InvalidOperationException("Failed to start 'dotnet' process - is the .NET SDK on PATH?");

            bool exited = process.WaitForExit(120_000);
            if (!exited)
            {
                // Round 4 review (P13): kill the orphan process tree before the assertion fails so
                // tempdir cleanup is not racing a still-running dotnet that holds file handles.
                // Round 4 external (P9): fail loud on kill failure and assert the second WaitForExit
                // actually drained the child, otherwise the subsequent Directory.Delete races a live
                // handle.
                bool killSucceeded = true;
                string? killFailureMessage = null;
                try
                {
                    process.Kill(entireProcessTree: true);
                }
                catch (InvalidOperationException invalid)
                {
                    killSucceeded = false;
                    killFailureMessage = invalid.Message;
                }

                bool drained = process.WaitForExit(10_000);
                killSucceeded.ShouldBeTrue($"process.Kill threw InvalidOperationException: {killFailureMessage}; the original 120s timeout cannot be diagnosed because the child was already gone or in an unexpected state.");
                drained.ShouldBeTrue("process.Kill(entireProcessTree: true) did not finish draining the child within 10s; tempdir cleanup would race a live handle.");
                exited.ShouldBeTrue("dotnet msbuild GenerateHexalithFoldersIdempotencyHelpers did not exit within 120s; orphan process killed.");
            }

            string combinedOutput = process.StandardOutput.ReadToEnd() + process.StandardError.ReadToEnd();
            process.ExitCode.ShouldBe(0, combinedOutput);
            File.Exists(output).ShouldBeTrue();
            File.ReadAllText(output).ShouldNotBe(File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Generated", "HexalithFoldersIdempotencyHelpers.g.cs")));
        }
        finally
        {
            Directory.Delete(tempRoot, recursive: true);
        }
    }

    [Fact]
    public void CanonicalHasherFailsClosedForMalformedMetadata()
    {
        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Test", [
            new IdempotencyField("z_field", true, "last"),
            new IdempotencyField("a_field", true, "first"),
        ]));

        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Test", [
            new IdempotencyField("a_field", true, "first"),
            new IdempotencyField("a_field", true, "duplicate"),
        ]));

        Should.Throw<Newtonsoft.Json.JsonReaderException>(() => HexalithIdempotencyHasher.NormalizeJsonText("{\"operation_id\":\"a\",\"operation_id\":\"b\"}"));
    }

    [Fact]
    public void IdempotencyEncodingCorpusIsConsumedForParserPolicyCases()
    {
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(Path.Combine(RepositoryRoot, "tests", "fixtures", "idempotency-encoding-corpus.json")));
        JsonElement[] cases = document.RootElement.GetProperty("cases").EnumerateArray().ToArray();

        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("NFC");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("NFD");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("ULID casing");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("percent-encoding");
        cases.Select(c => c.GetProperty("category").GetString()).ShouldContain("duplicate-json-key");
        cases.All(c => c.GetProperty("synthetic_data_only").GetBoolean()).ShouldBeTrue();
        cases.Any(c => c.GetProperty("contains_payload_material").GetBoolean()).ShouldBeFalse();

        JsonElement duplicateKey = cases.Single(c => c.GetProperty("category").GetString() == "duplicate-json-key");
        Should.Throw<Newtonsoft.Json.JsonReaderException>(() => HexalithIdempotencyHasher.NormalizeJsonText(duplicateKey.GetProperty("input").GetString()!));

        foreach (JsonElement corpusCase in cases.Where(c => c.GetProperty("category").GetString() != "duplicate-json-key"))
        {
            string classification = corpusCase.GetProperty("equivalence_classification").GetString() ?? string.Empty;
            string caseId = corpusCase.GetProperty("id").GetString() ?? "<unidentified>";
            string left = ComputeCorpusHash(corpusCase.GetProperty("input"));
            string right = ComputeCorpusHash(corpusCase.GetProperty("comparison_input"));

            if (classification.StartsWith("non-equivalent", StringComparison.Ordinal) ||
                classification.StartsWith("equivalent-only", StringComparison.Ordinal))
            {
                left.ShouldNotBe(right, caseId);
            }
            else if (classification == "parser-rejected")
            {
                // The corpus's parser-rejected classification describes behavior at the HTTP
                // idempotency-key parser boundary (Idempotency-Key header validation) — the input
                // is rejected before any hash computation. The canonical-hasher boundary here is
                // downstream of that validation; for hash purposes the two corpus inputs simply
                // produce non-equivalent escaped hashes. The HTTP parser-rejection contract is
                // enforced by the input validators in Hexalith.Folders.Server (Epic 4).
                // Round 4 review (P12) made this layering explicit.
                left.ShouldNotBe(right, caseId);
            }
            else if (classification == "equivalent-after-lexicographic-field-ordering")
            {
                left.ShouldBe(right, caseId);
            }
            else if (classification == "equivalent-after-generated-normalization-for-declared-normalization-insensitive-field" ||
                     classification == "equivalent-only-when-field-declares-compatibility-normalization")
            {
                // Default hasher does not apply generated normalization or compatibility normalization;
                // AC 6 reads "Unicode normalization where declared" and no current spine field declares
                // normalization-eligibility. When a field declares opt-in, a normalization-enabled
                // helper variant will flip this assertion. Tracked in deferred-work.md (Round 4).
                left.ShouldNotBe(right, caseId);
            }
            else
            {
                throw new InvalidOperationException(
                    $"Unhandled equivalence_classification '{classification}' for case '{caseId}'. Add an explicit branch when the corpus grows new classification values.");
            }
        }
    }

    [Fact]
    public void ApiExceptionExposesTypedProblemDetails()
    {
        var problem = new ProblemDetails
        {
            Category = CanonicalErrorCategory.Validation_error,
            ClientAction = ProblemDetailsClientAction.Revise_request,
            Code = "validation_error",
            CorrelationId = "correlation_01HZY7Z6N7J4Q2X8Y9V0COR001",
            Message = "Synthetic validation failure.",
            Retryable = false,
        };

        var typed = new HexalithFoldersApiException<ProblemDetails>("message", 400, "{}", new Dictionary<string, IEnumerable<string>>(), problem, null!);
        typed.ProblemDetails.ShouldBeSameAs(problem);

        string response = JsonConvert.SerializeObject(problem);
        var untyped = new HexalithFoldersApiException("message", 400, response, new Dictionary<string, IEnumerable<string>>(), null!);
        untyped.ProblemDetails.ShouldNotBeNull().Code.ShouldBe("validation_error");
        untyped.ProblemDetailsParseDiagnostic.ShouldBeNull();

        var malformed = new HexalithFoldersApiException("message", 400, "{not valid json", new Dictionary<string, IEnumerable<string>>(), null!);
        malformed.ProblemDetails.ShouldBeNull();
        malformed.ProblemDetailsParseDiagnostic.ShouldNotBeNull();
    }

    [Fact]
    public void HelperGeneratorProjectIsBuildTimeInput()
    {
        string project = Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Client", "Hexalith.Folders.Client.csproj");
        XDocument document = XDocument.Load(project);

        XElement target = document.Descendants("Target").Single(e => e.Attribute("Name")?.Value == "GenerateHexalithFoldersIdempotencyHelpers");
        target.Attribute("BeforeTargets")?.Value.ShouldBe("BeforeCompile");
        target.Attribute("Inputs")?.Value.ShouldContain("$(HexalithFoldersHelperGeneratorProject)");
        target.Attribute("Inputs")?.Value.ShouldContain("Generation\\Program.cs");
        target.Attribute("Outputs")?.Value.ShouldBe("$(HexalithFoldersGeneratedHelpers)");
        target.Descendants("Exec").Single().Attribute("Command")?.Value.ShouldContain("$(HexalithFoldersHelperGeneratorProject)");
    }

    [Fact]
    public void CanonicalHasherPinsPrimitiveEdgeFormatting()
    {
        HexalithIdempotencyHasher.Compute("Primitive", [new IdempotencyField("value", true, int.MinValue)]).ShouldBe(ExpectedHash("operation=Primitive", "field=value;present=true;value=n:-2147483648"));
        HexalithIdempotencyHasher.Compute("Primitive", [new IdempotencyField("value", true, ulong.MaxValue)]).ShouldBe(ExpectedHash("operation=Primitive", "field=value;present=true;value=n:18446744073709551615"));
        HexalithIdempotencyHasher.Compute("Primitive", [new IdempotencyField("value", true, 0)]).ShouldBe(ExpectedHash("operation=Primitive", "field=value;present=true;value=n:0"));
        HexalithIdempotencyHasher.Compute("Primitive", [new IdempotencyField("value", true, -1)]).ShouldBe(ExpectedHash("operation=Primitive", "field=value;present=true;value=n:-1"));
        HexalithIdempotencyHasher.Compute("Primitive", [new IdempotencyField("value", true, 1.0m)])
            .ShouldNotBe(HexalithIdempotencyHasher.Compute("Primitive", [new IdempotencyField("value", true, 1.00m)]));
        Should.Throw<InvalidOperationException>(() => HexalithIdempotencyHasher.Compute("Primitive", [new IdempotencyField("value", true, DateTime.SpecifyKind(DateTime.UnixEpoch, DateTimeKind.Unspecified))]));
    }

    private static FileMutationRequest CreateFileMutation(FileMutationRequestFileOperationKind kind, object transportOperation) =>
        new()
        {
            FileOperationKind = kind,
            TransportOperation = transportOperation,
            OperationId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
            PathMetadata = new PathMetadata
            {
                NormalizedPath = "docs/readme.md",
                DisplayName = "readme.md",
                PathPolicyClass = "metadata_only",
                UnicodeNormalization = PathMetadataUnicodeNormalization.NFC,
            },
            ContentHashReference = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            RequestSchemaVersion = "v1",
        };

    private static string ExpectedHash(params string[] lines)
    {
        string canonical = string.Join('\n', lines);
        byte[] digest = SHA256.HashData(Encoding.UTF8.GetBytes(canonical));
        return "sha256:" + Convert.ToHexString(digest).ToLowerInvariant();
    }

    private static string ComputeCorpusHash(JsonElement value)
    {
        object? material = value.ValueKind switch
        {
            JsonValueKind.String => value.GetString(),
            JsonValueKind.Object => Newtonsoft.Json.Linq.JToken.Parse(value.GetRawText()),
            _ => value.GetRawText(),
        };

        return HexalithIdempotencyHasher.Compute("Corpus", [new IdempotencyField("synthetic_field", true, material)]);
    }

    private static IReadOnlyList<OpenApiOperation> LoadOperations()
    {
        YamlMappingNode root = YamlContractLoader.LoadYaml(Path.Combine(RepositoryRoot, "src", "Hexalith.Folders.Contracts", "openapi", "hexalith.folders.v1.yaml"));
        List<OpenApiOperation> operations = [];

        foreach (KeyValuePair<YamlNode, YamlNode> pathEntry in RequiredMapping(root, "paths").Children)
        {
            YamlMappingNode path = pathEntry.Value.ShouldBeMapping("path item");
            IReadOnlyList<OpenApiParameter> pathParameters = EnumerateParameters(path).ToArray();
            foreach (KeyValuePair<YamlNode, YamlNode> methodEntry in path.Children)
            {
                string method = methodEntry.Key.ShouldBeScalar("method").Value ?? string.Empty;
                if (method is not ("get" or "post" or "put" or "patch" or "delete"))
                {
                    continue;
                }

                YamlMappingNode operation = methodEntry.Value.ShouldBeMapping("operation");
                string operationId = RequiredScalar(operation, "operationId");
                string? requestSchema = TryReadRequestSchema(operation);
                IReadOnlyList<string> fields = ReadStringSequence(operation, "x-hexalith-idempotency-equivalence");
                IReadOnlyList<OpenApiParameter> parameters = [.. pathParameters, .. EnumerateParameters(operation)];
                operations.Add(new OpenApiOperation(operationId, requestSchema, fields, parameters));
            }
        }

        return operations;
    }

    private static IEnumerable<OpenApiParameter> EnumerateParameters(YamlMappingNode mapping)
    {
        if (!mapping.Children.TryGetValue(new YamlScalarNode("parameters"), out YamlNode? parametersNode))
        {
            yield break;
        }

        foreach (YamlNode parameterNode in parametersNode.ShouldBeSequence("parameters"))
        {
            YamlMappingNode parameter = parameterNode.ShouldBeMapping("parameter");
            string name = parameter.Children.TryGetValue(new YamlScalarNode("$ref"), out YamlNode? referenceNode)
                ? (referenceNode.ShouldBeScalar("$ref").Value ?? string.Empty).Split('/').Last()
                : RequiredScalar(parameter, "name");
            yield return new OpenApiParameter(NormalizeName(name), name);
        }
    }

    private static string LocateRepositoryRoot()
    {
        // Assembly.Location returns "" under single-file publish; fall back to AppContext.BaseDirectory.
        string assemblyLocation = typeof(ClientGenerationTests).Assembly.Location;
        string startDirectoryPath = string.IsNullOrEmpty(assemblyLocation)
            ? AppContext.BaseDirectory
            : (Path.GetDirectoryName(assemblyLocation) ?? AppContext.BaseDirectory);

        DirectoryInfo? directory = new(startDirectoryPath);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Hexalith.Folders.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException("Could not locate Hexalith.Folders.slnx from the test assembly location.");
    }

    // ToCamelCase and NormalizeName now live in YamlContractLoader (Hexalith.Folders.Client.Generation.Shared)
    // so the generator and tests share one canonical implementation. Round 4 review (P8).
    private static string ToCamelCase(string snakeOrKebab) => YamlContractLoader.ToParameterName(snakeOrKebab);

    private sealed record OpenApiOperation(string OperationId, string? RequestSchema, IReadOnlyList<string> IdempotencyFields, IReadOnlyList<OpenApiParameter> Parameters);

    private sealed record OpenApiParameter(string Field, string Name);
}

