#!/usr/bin/env python3
"""Generate the server's operation-bound PD10 v2 response catalog."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


HTTP_METHODS = {"delete", "get", "head", "options", "patch", "post", "put", "trace"}


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def string_literal(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def tuple_key(entry: dict[str, Any]) -> str:
    return "|".join(
        (
            str(entry["status"]),
            entry["category"],
            entry["code"],
            "true" if entry["retryable"] else "false",
            entry["clientAction"],
            ",".join(sorted(entry["detailKeys"])),
        )
    )


def generate(contract: dict[str, Any]) -> str:
    operations: list[dict[str, Any]] = []
    for path_item in contract["paths"].values():
        for method, operation in path_item.items():
            if method in HTTP_METHODS and isinstance(operation, dict) and "operationId" in operation:
                operations.append(operation)
    operations.sort(key=lambda operation: operation["operationId"])
    if len(operations) != 49:
        raise ValueError(f"Expected 49 operations, found {len(operations)}.")

    lines = [
        "// <auto-generated />",
        "#nullable enable",
        "",
        "namespace Hexalith.Folders.Server;",
        "",
        "/// <summary>Operation-bound statuses and normalized problem tuples generated from the PD10 v2 contract.</summary>",
        "internal static class Pd10V2RuntimeResponseCatalog",
        "{",
        "    private static readonly IReadOnlyDictionary<string, HashSet<int>> Statuses =",
        "        new Dictionary<string, HashSet<int>>(StringComparer.Ordinal)",
        "        {",
    ]
    for operation in operations:
        statuses = sorted(int(status) for status in operation["responses"] if str(status).isdigit())
        lines.append(
            f"            [{string_literal(operation['operationId'])}] = [{', '.join(map(str, statuses))}],"
        )
    lines.extend(
        [
            "        };",
            "",
            "    private static readonly IReadOnlyDictionary<string, HashSet<string>> ProblemTuples =",
            "        new Dictionary<string, HashSet<string>>(StringComparer.Ordinal)",
            "        {",
        ]
    )
    for operation in operations:
        inventory = operation.get("x-hexalith-runtime-problem-inventory")
        if not isinstance(inventory, list) or not inventory:
            raise ValueError(f"Operation {operation['operationId']} has no runtime problem inventory.")
        values = sorted({tuple_key(entry) for entry in inventory})
        lines.append(f"            [{string_literal(operation['operationId'])}] =")
        lines.append("            [")
        lines.extend(f"                {string_literal(value)}," for value in values)
        lines.append("            ],")
    lines.extend(
        [
            "        };",
            "",
            "    /// <summary>Returns whether an HTTP status is declared for the operation.</summary>",
            "    internal static bool AllowsStatus(string operationId, int status)",
            "        => Statuses.TryGetValue(operationId, out HashSet<int>? values) && values.Contains(status);",
            "",
            "    /// <summary>Returns whether a normalized problem tuple is declared for the operation.</summary>",
            "    internal static bool AllowsProblem(string operationId, string tuple)",
            "        => ProblemTuples.TryGetValue(operationId, out HashSet<string>? values) && values.Contains(tuple);",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    arguments = parse_arguments()
    if arguments.contract.resolve() == arguments.output.resolve():
        raise ValueError("Runtime catalog output must not alias the contract input.")
    contract = yaml.safe_load(arguments.contract.read_text(encoding="utf-8"))
    output = generate(contract)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(output, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
