namespace Hexalith.Folders.Aggregates.Folder;

public enum FolderResultCode
{
    Accepted,
    Created,
    IdempotentReplay,
    AlreadyApplied,
    MissingEntry,
    DuplicateEntry,
    IdempotencyConflict,
    IdempotencyUnavailable,
    DuplicateFolder,
    AppendConflict,
    InvalidFolderId,
    InvalidFolderMetadata,
    InvalidTenant,
    ReservedTenant,
    MissingAuthoritativeTenant,
    TenantAccessDenied,
    FolderAclDenied,
    AclEvidenceUnavailable,
    AclEvidenceMismatch,
    FolderNotFound,
    UnsupportedAction,
    InvalidPrincipal,
    ValidationFailed,
    StaleProjection,
    UnavailableProjection,
    UnknownTenant,
    DisabledTenant,
    MalformedEvidence,
    TenantMismatch,
    ReplayConflict,
    StateTransitionInvalid,
}
